### ISSUE TITLE
Search cards UI

### ISSUE THREAD

**Issue by kalashshah** [AkhileshManda/programmer-profile-flutter-app#8]
- Update search cards UI
  - Add description to search card and change colours

- Update search bar UI
  - Add border radius and padding

**Comment by AkhileshManda** [comment]
![image](https://user-images.githubusercontent.com/70640191/221251357-b0b03b2c-58b0-4378-8cde-0168ce3a5351.png)

**Comment by AkhileshManda** [comment]
@kalashshah please suggest a good icon for unfollowing

**Comment by AkhileshManda** [comment]
Fixed with commit [63612b9](https://github.com/AkhileshManda/programmer-profile-flutter-app/commit/63612b95f80fe91f920714a96be91c168ccd7095)
